.travis.yml
src/vaadin-cookie-consent.html
test/change-texts-test.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-cookie-consent/16)

Removed gemini tests

---

bower.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-cookie-consent/20)

Fix license

---

.gitignore

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-cookie-consent/22)

Ignore IDEA

---

analysis.json
bower.json
demo/demos.json
demo/element-basic-demos.html
demo/element-customize-texts.html
demo/element-theming.html
demo/index.html
src/vaadin-cookie-consent.html

vaadin/vaadin-cookie-consent#9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-cookie-consent/23)

Improve vaadincom pages

---

README.md

Inspired by https://github.com/vaadin/vaadin-charts/blob/master/README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-cookie-consent/27)

Improvements to the Getting Started material in README

---

bower.json
demo/element-basic-demos.html
demo/element-customize-texts.html
demo/element-theming.html
demo/index.html
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-cookie-consent/24)

Fix demos in vaadincom

---

package.json
src/vaadin-cookie-consent.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-cookie-consent/28)

Release v1.0.0 beta2

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-cookie-consent/32)

add a credit to SauceLabs into README

---

package.json
src/vaadin-cookie-consent.html
test/.eslintrc.json
test/accessibility-test.html
test/test-suites.js

inspired by https://github.com/Polymer/pwa-starter-kit/blob/master/test/unit/views-a11y.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-cookie-consent/29)

add aXe-based automatic accesibility test

---

gulpfile.js
package.json
src/vaadin-cookie-consent.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-cookie-consent/33)

prepare 1.0.0

---

demo/element-basic-demos.html

Fixes #36
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-cookie-consent/45)

Change image links to be displayed properly on vaadin com

---

analysis.json
src/vaadin-cookie-consent.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-cookie-consent/48)

Add documentation how to theme the element

---

.travis.yml
bower.json
package.json
src/vaadin-cookie-consent.html
wct.conf.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-cookie-consent/51)

1.1.0-alpha2

---

analysis.json
package.json
src/vaadin-cookie-consent.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-cookie-consent/52)

Pick changes for 1.0.1

---

package.json
src/vaadin-cookie-consent.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-cookie-consent/53)

Version 1.0.2

---

bower.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-cookie-consent/57)

Use stable license checker [skip ci]

---

package.json
src/vaadin-cookie-consent.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-cookie-consent/58)

Version 1.1.0

---

magi-p3-post.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-cookie-consent/60)

Add cookieconsent dep in magi p3 post conversion

---

.travis.yml
test/test-suites.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-cookie-consent/61)

Update to xenial

---

src/vaadin-cookie-consent.html

Connected to vaadin/vaadin-core#257

docs: add JSDoc for attributes [skip ci]

---

package.json
src/vaadin-cookie-consent.html

cherry-pick of vaadin/web-components#3831 and vaadin/web-components#3832
related-to vaadin/web-components#3773

chore: Add cvdlName metadata
